"""
JS Backend.

v0.003 milestone (extended in v0.003). ARKlight does not compile Python
to JavaScript, and components do not accept arbitrary JS strings --
both would break "the browser never executes Python" in spirit and
"one obvious way" in practice (every site inventing its own inline-JS
dialect). Instead, following the same model as Alpine.js/htmx (describe
behavior with HTML attributes; a small shipped runtime does the rest,
no build step), ARKlight ships one static `arklight.js` implementing a
fixed, documented vocabulary of behaviors:

- `toggle`     -- toggles a CSS class on `target` element(s). Which
                  class is controlled by `toggle_class` (default
                  "is-open"). This is enough for menus, accordions,
                  and disclosure widgets without writing any JS.
- `scroll-to`  -- smooth-scrolls `target` into view.
- `copy`       -- copies `target`'s text content to the clipboard, and
                  briefly swaps the clicked element's own text to
                  confirm it worked (a "Copy" button next to a code
                  snippet or a share link).
- `dismiss`    -- adds `toggle_class` (default "hidden") to `target`
                  element(s) and leaves it there -- a one-way hide, for
                  closing a banner/alert/cookie-notice permanently
                  rather than toggling it back and forth.

A component opts in with `on_click="toggle"` (or `"scroll-to"`,
`"copy"`, `"dismiss"`) plus a `target="<css selector>"` prop --
validated against `arklight.ir.schema.KNOWN_BEHAVIORS` at the
Validation stage, so a typo in a behavior name is caught at build time,
not silently ignored in the browser.

Every behavior here is stateless in the same sense `toggle` always was:
each is a pure reaction to a single click, computed from the DOM at
that moment (read a class, read some text, write it to the clipboard).
None of them retain a JS-side value across events or otherwise give the
runtime memory -- that's still the explicit non-goal (see
docs/DESIGN-NOTES.md), not something v0.003 relaxed.

The runtime also auto-highlights the current page's nav link (any `<a>`
inside `.nav` whose resolved URL matches the current page) with an
`is-active` class -- zero wiring required, since every site with a
`nav()` gets this for free.

This is intentionally a static, constant JS file for v0.003, same
shape as the CSS backend: no per-node code generation yet. Extending
`KNOWN_BEHAVIORS` + the `behaviors` object below together is how future
milestones add more built-ins without changing the Backend interface.
"""

from __future__ import annotations

from arklight.backend.base import Backend
from arklight.ir.build import WebsiteIR

# Where the HTML backend expects to find the generated runtime,
# relative to the output directory root.
SCRIPT_PATH = "arklight.js"

RUNTIME_JS = """\
// Generated by ARKlight -- v0.003 behavior runtime.
// Implements exactly the behaviors in arklight.ir.schema.KNOWN_BEHAVIORS:
// "toggle", "scroll-to", "copy", "dismiss". No other JavaScript runs on
// this site.
(function () {
  "use strict";

  var behaviors = {
    toggle: function (el) {
      var selector = el.getAttribute("data-ark-target");
      var className = el.getAttribute("data-ark-toggle-class") || "is-open";
      if (!selector) return;
      document.querySelectorAll(selector).forEach(function (target) {
        target.classList.toggle(className);
      });
    },
    "scroll-to": function (el) {
      var selector = el.getAttribute("data-ark-target");
      if (!selector) return;
      var target = document.querySelector(selector);
      if (target && target.scrollIntoView) {
        target.scrollIntoView({ behavior: "smooth" });
      }
    },
    copy: function (el) {
      var selector = el.getAttribute("data-ark-target");
      if (!selector) return;
      var target = document.querySelector(selector);
      if (!target || !navigator.clipboard) return;
      var text = target.value !== undefined && target.tagName === "TEXTAREA"
        ? target.value
        : target.textContent;
      navigator.clipboard.writeText(text.trim()).then(function () {
        var original = el.textContent;
        el.textContent = "Copied!";
        setTimeout(function () {
          el.textContent = original;
        }, 1500);
      });
    },
    dismiss: function (el) {
      var selector = el.getAttribute("data-ark-target");
      var className = el.getAttribute("data-ark-toggle-class") || "hidden";
      if (!selector) return;
      document.querySelectorAll(selector).forEach(function (target) {
        target.classList.add(className);
      });
    }
  };

  function wireBehaviors() {
    document.querySelectorAll("[data-ark-on-click]").forEach(function (el) {
      var name = el.getAttribute("data-ark-on-click");
      var behavior = behaviors[name];
      if (!behavior) return;
      el.addEventListener("click", function (event) {
        event.preventDefault();
        behavior(el);
      });
    });
  }

  function highlightActiveNavLink() {
    document.querySelectorAll(".nav a").forEach(function (link) {
      var here = location.href.replace(/#.*$/, "");
      var there = link.href.replace(/#.*$/, "");
      if (there === here) {
        link.classList.add("is-active");
      }
    });
  }

  document.addEventListener("DOMContentLoaded", function () {
    wireBehaviors();
    highlightActiveNavLink();
  });
})();
"""


class JSBackend(Backend):
    name = "js"

    def render(self, ir: WebsiteIR) -> dict[str, str]:
        # Same shape as CSSBackend: a single constant runtime for now.
        # `ir` is accepted (Backend interface) but not yet consulted --
        # reserved for a future pass that only emits the behaviors a
        # site actually uses.
        del ir
        return {SCRIPT_PATH: RUNTIME_JS}
