"""
ARKlight -- a Python-first compiler for building static websites.

    from arklight import *

    site = Site()

    @site.page("/")
    def home():
        return Page(
            Heading("ARKlight"),
            Text("Build websites with Python."),
            Button("Get Started"),
        )

Users write Python. ARKlight compiles it to standard HTML.
The browser never executes Python.
"""

from arklight.api import (
    Site,
    Page,
    Heading,
    Text,
    Button,
    Container,
    Link,
    Image,
    List,
    Item,
    Header,
    Footer,
    Main,
    Nav,
    Section,
    Article,
    Aside,
    Figure,
    FigCaption,
    Details,
    Summary,
    Strong,
    Em,
    Small,
    Mark,
    Code,
    Cite,
    Abbr,
    Sub,
    Sup,
    Span,
    Time,
    HorizontalRule,
    LineBreak,
    Pre,
    Blockquote,
    Form,
    Input,
    Textarea,
    Select,
    Option,
    OptGroup,
    Label,
    FieldSet,
    Legend,
    Table,
    TableHead,
    TableBody,
    TableFoot,
    TableRow,
    TableHeaderCell,
    TableCell,
    Caption,
    Video,
    Audio,
    Source,
    # v0.003 second vocabulary extension addendum ("even more
    # vocabulary") -- previously defined in arklight/api.py but missing
    # from this package's `import` list, so `from arklight import *`
    # couldn't reach them even though `from arklight.api import Picture`
    # (etc.) worked. See docs/DESIGN-NOTES.md, "v0.004: CLI scaffolding
    # (`arklight new`)", for how this was found.
    OrderedList,
    DescriptionList,
    DescriptionTerm,
    DescriptionDetails,
    Picture,
    PictureSource,
    Progress,
    Meter,
    Datalist,
    Output,
    Dialog,
    Kbd,
    Samp,
    Var,
    Data,
    Ins,
    Del,
    Q,
    Dfn,
    Address,
    Wbr,
    Bdi,
    Bdo,
    Ruby,
    Rt,
    Rp,
    ColGroup,
    Col,
    Track,
    Map,
    Area,
    IFrame,
    NoScript,
    State,
    Bind,
    Action,
    ActionRef,
    ARKNode,
)

__version__ = "0.0436"

__all__ = [
    "Site",
    "Page",
    "Heading",
    "Text",
    "Button",
    "Container",
    "Link",
    "Image",
    "List",
    "Item",
    "Header",
    "Footer",
    "Main",
    "Nav",
    "Section",
    "Article",
    "Aside",
    "Figure",
    "FigCaption",
    "Details",
    "Summary",
    "Strong",
    "Em",
    "Small",
    "Mark",
    "Code",
    "Cite",
    "Abbr",
    "Sub",
    "Sup",
    "Span",
    "Time",
    "HorizontalRule",
    "LineBreak",
    "Pre",
    "Blockquote",
    "Form",
    "Input",
    "Textarea",
    "Select",
    "Option",
    "OptGroup",
    "Label",
    "FieldSet",
    "Legend",
    "Table",
    "TableHead",
    "TableBody",
    "TableFoot",
    "TableRow",
    "TableHeaderCell",
    "TableCell",
    "Caption",
    "Video",
    "Audio",
    "Source",
    "OrderedList",
    "DescriptionList",
    "DescriptionTerm",
    "DescriptionDetails",
    "Picture",
    "PictureSource",
    "Progress",
    "Meter",
    "Datalist",
    "Output",
    "Dialog",
    "Kbd",
    "Samp",
    "Var",
    "Data",
    "Ins",
    "Del",
    "Q",
    "Dfn",
    "Address",
    "Wbr",
    "Bdi",
    "Bdo",
    "Ruby",
    "Rt",
    "Rp",
    "ColGroup",
    "Col",
    "Track",
    "Map",
    "Area",
    "IFrame",
    "NoScript",
    "State",
    "Bind",
    "Action",
    "ActionRef",
    "ARKNode",
    "__version__",
]
