"""
PWA (Progressive Web App) support -- v0.038.

Incremental, opt-in post-build step: turns an existing `arklight
build` output directory into an installable PWA by generating a Web
App Manifest and a Service Worker, then injecting the two small tags
each page needs to pick them up (`<link rel="manifest">` and an inline
registration script) into every already-built HTML file.

Like `arklight.packer.bundle`, this module only ever reads files a
normal build already produced -- it does not import or touch the
compiler pipeline (parser/ir/backend). That keeps PWA-enabling a step
*after* `arklight build`, not a new pipeline stage fused into it, and
it's what makes it safe to run repeatedly: `enable_pwa()` re-scans
`build_dir` every time and rewrites `manifest.json`/`sw.js` plus the
injected tags in place -- nothing is appended twice, and edits to the
build (new pages, changed assets) are picked up on the next run
without cleaning anything up by hand first. That's the "incremental"
part: there's no separate PWA build mode to keep in sync, just re-run
`arklight pwa <build-dir>` after any `arklight build`.

    build-dir/
      index.html, about.html, ...   <- get manifest link/meta + SW
                                        registration injected in place
      manifest.json                 <- generated
      sw.js                         <- generated, precaches every file
                                        found in build-dir at run time

The service worker is a small, dependency-free, cache-first precache:
every file `enable_pwa()` finds in `build_dir` (HTML/CSS/JS/assets/
anything else) is listed and precached on install; `CACHE_NAME` embeds
a content hash of that file list, so any change to the build (added,
removed, or edited file) yields a new cache name -- that's what
actually triggers the browser to fetch the update on the next visit,
via the generated `sw.js`'s own `activate` handler dropping any
differently-named cache. An unchanged re-run produces the same cache
name and is a no-op for anyone with it already installed.
"""

from __future__ import annotations

import hashlib
import json
import posixpath
import re
from dataclasses import dataclass, field
from pathlib import Path

MANIFEST_NAME = "manifest.json"
SERVICE_WORKER_NAME = "sw.js"

# Injected verbatim into every page's <head>/<body>, wrapped in these
# marker comments so re-running enable_pwa() finds and replaces its
# own prior injection instead of appending a second copy each time.
_HEAD_MARKER_START = "<!-- arklight:pwa:head -->"
_HEAD_MARKER_END = "<!-- /arklight:pwa:head -->"
_SW_MARKER_START = "<!-- arklight:pwa:sw -->"
_SW_MARKER_END = "<!-- /arklight:pwa:sw -->"

_HEAD_BLOCK_RE = re.compile(
    re.escape(_HEAD_MARKER_START) + r".*?" + re.escape(_HEAD_MARKER_END) + r"\n?",
    re.DOTALL,
)
_SW_BLOCK_RE = re.compile(
    re.escape(_SW_MARKER_START) + r".*?" + re.escape(_SW_MARKER_END) + r"\n?",
    re.DOTALL,
)
_HEAD_CLOSE_RE = re.compile(r"</head>", re.IGNORECASE)
_BODY_CLOSE_RE = re.compile(r"</body>", re.IGNORECASE)


class PWAError(Exception):
    """Raised when a build directory can't be turned into a PWA."""


@dataclass
class PWAResult:
    build_dir: Path
    manifest_path: Path
    service_worker_path: Path
    updated_pages: list[str] = field(default_factory=list)
    cached_paths: list[str] = field(default_factory=list)
    cache_name: str = ""


def _cache_name(paths: list[Path], build_dir: Path) -> str:
    """
    Content hash of every precached file's relative path *and* bytes,
    so any change to the build -- a new file, a removed one, an edited
    one -- changes the cache name. See the module docstring for why
    that's what makes a re-run an effective cache-bust.
    """
    digest = hashlib.sha256()
    for path in paths:
        digest.update(path.relative_to(build_dir).as_posix().encode("utf-8"))
        digest.update(path.read_bytes())
    return f"arklight-pwa-{digest.hexdigest()[:16]}"


def _render_manifest(
    *,
    name: str,
    short_name: str | None,
    start_url: str,
    theme_color: str,
    background_color: str,
    display: str,
    icons: list[dict[str, str]],
) -> str:
    manifest = {
        "name": name,
        "short_name": short_name or name[:12],
        "start_url": start_url,
        "scope": "./",
        "display": display,
        "theme_color": theme_color,
        "background_color": background_color,
        "icons": icons,
    }
    return json.dumps(manifest, indent=2) + "\n"


def _render_service_worker(cache_name: str, precache_paths: list[str]) -> str:
    precache_json = json.dumps(sorted(set(precache_paths + [MANIFEST_NAME])), indent=2)
    return (
        "// Generated by `arklight pwa` -- do not edit by hand. Re-run\n"
        "// `arklight pwa <build-dir>` after your next `arklight build`\n"
        "// instead; this file (including CACHE_NAME) is fully\n"
        "// regenerated every time, not patched in place.\n"
        f'const CACHE_NAME = "{cache_name}";\n'
        f"const PRECACHE_URLS = {precache_json};\n"
        "\n"
        'self.addEventListener("install", (event) => {\n'
        "  event.waitUntil(\n"
        "    caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE_URLS))\n"
        "  );\n"
        "  self.skipWaiting();\n"
        "});\n"
        "\n"
        'self.addEventListener("activate", (event) => {\n'
        "  event.waitUntil(\n"
        "    caches.keys().then((names) =>\n"
        "      Promise.all(\n"
        "        names.filter((name) => name !== CACHE_NAME).map((name) => caches.delete(name))\n"
        "      )\n"
        "    )\n"
        "  );\n"
        "  self.clients.claim();\n"
        "});\n"
        "\n"
        'self.addEventListener("fetch", (event) => {\n'
        "  event.respondWith(\n"
        "    caches.match(event.request).then((cached) => cached || fetch(event.request))\n"
        "  );\n"
        "});\n"
    )


def _relative_href(target_name: str, page_rel_path: str) -> str:
    """`target_name` (e.g. "manifest.json", root-level) relative to a
    page's own directory -- same approach the HTML backend already
    uses for stylesheet/script hrefs, see
    `arklight.backend.html.render._relative_asset_path`."""
    current_dir = posixpath.dirname(page_rel_path) or "."
    return posixpath.relpath(target_name, current_dir)


def _inject_page(html: str, *, manifest_href: str, sw_href: str, theme_color: str) -> str:
    head_block = (
        f"{_HEAD_MARKER_START}\n"
        f'  <link rel="manifest" href="{manifest_href}">\n'
        f'  <meta name="theme-color" content="{theme_color}">\n'
        f"{_HEAD_MARKER_END}\n"
    )
    sw_block = (
        f"{_SW_MARKER_START}\n"
        "  <script>\n"
        '    if ("serviceWorker" in navigator) {\n'
        '      window.addEventListener("load", () => {\n'
        f'        navigator.serviceWorker.register("{sw_href}");\n'
        "      });\n"
        "    }\n"
        "  </script>\n"
        f"{_SW_MARKER_END}\n"
    )

    # Strip any previously-injected blocks first -- re-running enable_pwa()
    # replaces its own output rather than piling up duplicate copies.
    html = _HEAD_BLOCK_RE.sub("", html)
    html = _SW_BLOCK_RE.sub("", html)

    if not _HEAD_CLOSE_RE.search(html):
        raise PWAError("Could not find </head> to inject the PWA manifest link into.")
    if not _BODY_CLOSE_RE.search(html):
        raise PWAError("Could not find </body> to inject the service worker registration into.")

    html = _HEAD_CLOSE_RE.sub(head_block + "</head>", html, count=1)
    html = _BODY_CLOSE_RE.sub(sw_block + "</body>", html, count=1)
    return html


def enable_pwa(
    build_dir: str | Path,
    *,
    name: str,
    short_name: str | None = None,
    start_url: str = "index.html",
    theme_color: str = "#000000",
    background_color: str = "#ffffff",
    display: str = "standalone",
    icons: list[dict[str, str]] | None = None,
) -> PWAResult:
    """
    Turn `build_dir` (an existing `arklight build` output directory)
    into a PWA: writes `manifest.json` + `sw.js` into it and injects
    the tags every `.html` page needs to pick them up.

    Safe to call repeatedly on the same directory -- see the module
    docstring's "incremental" note. Raises PWAError if `build_dir`
    doesn't exist or contains no `.html` files (i.e. doesn't look like
    an `arklight build` output directory).
    """
    build_dir = Path(build_dir)
    if not build_dir.is_dir():
        raise PWAError(f"Build directory not found: {build_dir}")

    html_paths = sorted(build_dir.rglob("*.html"))
    if not html_paths:
        raise PWAError(
            f"No .html files found in {build_dir} -- run `arklight build` first, "
            f"then enable PWA on its output directory."
        )

    manifest_path = build_dir / MANIFEST_NAME
    sw_path = build_dir / SERVICE_WORKER_NAME

    # Inject/write every page *before* computing the precache hash, so
    # the hash always covers each page's final (post-injection) bytes
    # -- otherwise a first run (hashing pre-injection pages) and a
    # second run (hashing the first run's already-injected pages)
    # would produce different cache names for what is, from the
    # outside, an unchanged build. See the module docstring.
    updated_pages: list[str] = []
    for page_path in html_paths:
        page_rel = page_path.relative_to(build_dir).as_posix()
        manifest_href = _relative_href(MANIFEST_NAME, page_rel)
        sw_href = _relative_href(SERVICE_WORKER_NAME, page_rel)
        original = page_path.read_text(encoding="utf-8")
        updated = _inject_page(
            original, manifest_href=manifest_href, sw_href=sw_href, theme_color=theme_color
        )
        if updated != original:
            page_path.write_text(updated, encoding="utf-8")
        updated_pages.append(page_rel)

    # Precache list/hash is computed from whatever's in build_dir now
    # (post-injection), excluding this run's own manifest.json/sw.js --
    # avoids hashing sw.js's own not-yet-written bytes into its own
    # cache name, and re-including a stale manifest.json from a prior
    # run in the new one's hash.
    precache_sources = sorted(
        p
        for p in build_dir.rglob("*")
        if p.is_file() and p not in (manifest_path, sw_path)
    )
    cache_name = _cache_name(precache_sources, build_dir)
    precache_rel = [p.relative_to(build_dir).as_posix() for p in precache_sources]

    manifest_path.write_text(
        _render_manifest(
            name=name,
            short_name=short_name,
            start_url=start_url,
            theme_color=theme_color,
            background_color=background_color,
            display=display,
            icons=icons or [],
        ),
        encoding="utf-8",
    )
    sw_path.write_text(_render_service_worker(cache_name, precache_rel), encoding="utf-8")

    return PWAResult(
        build_dir=build_dir,
        manifest_path=manifest_path,
        service_worker_path=sw_path,
        updated_pages=updated_pages,
        cached_paths=sorted(set(precache_rel + [MANIFEST_NAME])),
        cache_name=cache_name,
    )
