"""
CSS Backend.

v0.002 milestone. ARKlight ships one global stylesheet by default so a
freshly-generated site looks intentional out of the box, with zero CSS
written by the user -- matching "beginner friendly" and "Flask-like
simplicity". It targets the same tag mapping the HTML backend uses
(h1-h6, p, button, a, div, ul/li), plus a couple of small utility
classes (`.nav`, `.page`) that the built-in components can opt into via
the `class_name` prop.

Per-node customization doesn't require touching this file: any
component can carry a `style={...}` dict prop (rendered as an inline
`style` attribute by the HTML backend) or a `class_name="..."` prop
(rendered as `class`) to layer custom rules or override these defaults.

This is intentionally a static, constant stylesheet for v0.002 --
no per-node CSS generation yet. That's a natural place to extend later
(e.g. collecting `style=` props into real CSS rules instead of inline
styles) without changing the Backend interface.
"""

from __future__ import annotations

from arklight.backend.base import Backend
from arklight.ir.build import WebsiteIR

# Where the HTML backend expects to find the generated stylesheet,
# relative to the output directory root. Shared as a constant so both
# backends agree on the filename without importing each other's
# rendering internals.
STYLESHEET_PATH = "styles.css"

BASE_CSS_HEADER = """\
/* Generated by ARKlight -- v0.0431 default stylesheet.
   Override any of this with `style={...}` or `class_name="..."` props
   on your components. */
"""

# CSS backend refactor: the `:root` block used to be baked directly into
# BASE_CSS as a constant -- which is exactly why `--ark-max-width`
# (and, less visibly, `--ark-bg`) were structurally unreachable from any
# site-level API (see docs/CONTAINER-WIDTH-BUG.md and
# `Site.css_var_overrides` in arklight/api.py). This table is now the
# single source of truth for both the default value of every
# `:root`-declared `--ark-*` variable AND the order it's emitted in;
# `_render_root_and_property_rules` below reads it, merges in whatever
# a site passed via `Site(max_width=..., bg=...)`, and generates the
# `:root { ... }` block instead of it being hand-written CSS.
#
# Only variables `body` (or another element) reads *directly* belong
# here -- variables that already flow through a `var(--x, fallback)`
# call at their point of use (`--ark-grid-min`, `--ark-stack-space`,
# ...) are already reachable by a site overriding them via a `style=`
# prop on a wrapper, per the same reachability rule; adding them to
# this table is tracked as a follow-up, not done in this pass.
ROOT_VAR_DEFAULTS: dict[str, str] = {
    "--ark-bg": "#ffffff",
    "--ark-text": "#1a1a2e",
    "--ark-muted": "#5b5b76",
    "--ark-accent": "#4f46e5",
    "--ark-accent-hover": "#4338ca",
    "--ark-border": "#e5e5f0",
    # The one-line fix for the container-width bug: `min()` combines a
    # fluid bound (page never touches the viewport edge) with an
    # absolute cap (~1200px, wide enough for multi-column layouts,
    # narrow enough to stay readable) -- the same "intrinsic" idiom
    # (clamp/min/minmax) the rest of BASE_CSS already leans on for
    # .switcher/.grid/.fluid-heading, instead of a fixed 720px column.
    "--ark-max-width": "min(100% - 3rem, 75rem)",
}

# `@property` gives the browser (and a site author debugging output) a
# real type to check a `--ark-*` value against, instead of every custom
# property being an untyped string substitution where a typo
# (`--ark-max-width: 75re;`) fails silently. `syntax` values are CSS
# <syntax-string>s -- kept as a small table next to ROOT_VAR_DEFAULTS
# rather than hand-written per-variable, since it's mechanical to get
# right once and easy to get subtly wrong by hand each time.
ROOT_VAR_SYNTAX: dict[str, str] = {
    "--ark-bg": '"<color>"',
    "--ark-text": '"<color>"',
    "--ark-muted": '"<color>"',
    "--ark-accent": '"<color>"',
    "--ark-accent-hover": '"<color>"',
    "--ark-border": '"<color>"',
    "--ark-max-width": '"<length-percentage>"',
}

BASE_CSS_BODY = """\
* {
  box-sizing: border-box;
}

body {
  margin: 0;
  padding: 2.5rem 1.5rem 4rem;
  background: var(--ark-bg);
  color: var(--ark-text);
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial,
    sans-serif;
  line-height: 1.6;
  max-width: var(--ark-max-width);
  margin-left: auto;
  margin-right: auto;
}

h1, h2, h3, h4, h5, h6 {
  line-height: 1.25;
  margin: 1.6em 0 0.5em;
  font-weight: 700;
  letter-spacing: -0.01em;
  text-wrap: balance;
}

h1 { font-size: 2.25rem; margin-top: 0; }
h2 { font-size: 1.75rem; }
h3 { font-size: 1.4rem; }
h4 { font-size: 1.15rem; }
h5 { font-size: 1rem; }
h6 { font-size: 0.9rem; text-transform: uppercase; letter-spacing: 0.05em; color: var(--ark-muted); }

p {
  margin: 0 0 1em;
  color: var(--ark-text);
  text-wrap: pretty;
}

a {
  color: var(--ark-accent);
  text-decoration: none;
}

a:hover {
  color: var(--ark-accent-hover);
  text-decoration: underline;
}

button {
  font: inherit;
  background: var(--ark-accent);
  color: #ffffff;
  border: none;
  border-radius: 8px;
  padding: 0.65em 1.4em;
  cursor: pointer;
  transition: background 0.15s ease;
}

button:hover {
  background: var(--ark-accent-hover);
}

ul {
  padding-left: 1.25em;
  margin: 0 0 1em;
}

li {
  margin: 0.25em 0;
}

img {
  max-width: 100%;
  border-radius: 8px;
}

div {
  margin: 0;
}

/* Utility classes available to any component via class_name="..." */

.nav {
  display: flex;
  gap: 1.25rem;
  padding-bottom: 1.5rem;
  margin-bottom: 1.5rem;
  border-bottom: 1px solid var(--ark-border);
}

.nav a {
  color: var(--ark-text);
  font-weight: 600;
}

.nav a:hover {
  color: var(--ark-accent);
}

.nav a.is-active {
  color: var(--ark-accent);
}

.page {
  padding: 0;
}

/* Pairs with the "toggle" behavior (see arklight.backend.js): start an
   element hidden with class_name="hidden", then toggle_class="hidden"
   on the button that reveals it. */
.hidden {
  display: none;
}

.muted {
  color: var(--ark-muted);
}

.card {
  border: 1px solid var(--ark-border);
  border-radius: 12px;
  padding: 1.25rem 1.5rem;
  margin: 1em 0;
}

/* ------------------------------------------------------------------ */
/* v0.003 -- default styling for the extended tag vocabulary.          */
/* ------------------------------------------------------------------ */

header, footer, main, nav, section, article, aside {
  display: block;
}

header {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: clamp(0.5rem, 2vw, 1.5rem);
}

figure {
  margin: 1.5em 0;
}

figcaption {
  color: var(--ark-muted);
  font-size: 0.9rem;
  margin-top: 0.5em;
}

/* <details>/<summary>: a native disclosure widget -- no `toggle`
   behavior needed for a plain accordion. */
details {
  border: 1px solid var(--ark-border);
  border-radius: 8px;
  padding: 0.75em 1em;
  margin: 1em 0;
}

summary {
  cursor: pointer;
  font-weight: 600;
}

details[open] summary {
  margin-bottom: 0.5em;
}

strong { font-weight: 700; }
em { font-style: italic; }
small { font-size: 0.85em; color: var(--ark-muted); }
mark { background: #fef3c7; color: inherit; padding: 0.1em 0.2em; border-radius: 3px; }

code {
  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, "Liberation Mono", monospace;
  font-size: 0.9em;
  background: var(--ark-border);
  padding: 0.15em 0.4em;
  border-radius: 4px;
}

pre {
  background: #1a1a2e;
  color: #e5e5f0;
  padding: 1em 1.25em;
  border-radius: 8px;
  overflow-x: auto;
  margin: 1em 0;
}

pre code {
  background: none;
  padding: 0;
  color: inherit;
}

blockquote {
  border-left: 3px solid var(--ark-accent);
  margin: 1em 0;
  padding: 0.25em 0 0.25em 1.25em;
  color: var(--ark-muted);
}

hr {
  border: none;
  border-top: 1px solid var(--ark-border);
  margin: 2em 0;
}

abbr[title] {
  text-decoration: underline dotted;
  cursor: help;
}

time, cite {
  color: var(--ark-muted);
}

/* Forms. */

form {
  display: block;
  margin: 0;
}

fieldset {
  border: 1px solid var(--ark-border);
  border-radius: 8px;
  padding: 1em 1.25em;
  margin: 1em 0;
}

legend {
  font-weight: 600;
  padding: 0 0.4em;
}

label {
  display: block;
  font-weight: 600;
  margin: 0.75em 0 0.3em;
}

input, textarea, select {
  font: inherit;
  color: var(--ark-text);
  background: var(--ark-bg);
  border: 1px solid var(--ark-border);
  border-radius: 6px;
  padding: 0.55em 0.75em;
  width: 100%;
  max-width: 100%;
  box-sizing: border-box;
}

input:focus, textarea:focus, select:focus {
  outline: 2px solid var(--ark-accent);
  outline-offset: 1px;
}

textarea {
  resize: vertical;
  min-height: 6em;
  field-sizing: content;
}

input[type="checkbox"], input[type="radio"] {
  width: auto;
  margin-right: 0.5em;
}

/* Tables. */

table {
  width: 100%;
  border-collapse: collapse;
  margin: 1em 0;
}

caption {
  caption-side: top;
  text-align: left;
  color: var(--ark-muted);
  margin-bottom: 0.5em;
}

th, td {
  text-align: left;
  padding: 0.6em 0.9em;
  border-bottom: 1px solid var(--ark-border);
}

th {
  font-weight: 700;
  border-bottom-width: 2px;
}

/* Media. */

video, audio {
  max-width: 100%;
  border-radius: 8px;
}

audio {
  width: 100%;
}

picture img {
  max-width: 100%;
  border-radius: 8px;
}

/* ------------------------------------------------------------------ */
/* v0.003 -- default styling for the second vocabulary addendum.       */
/* ------------------------------------------------------------------ */

ol {
  padding-left: 1.25em;
  margin: 0 0 1em;
}

dl {
  margin: 0 0 1em;
}

dt {
  font-weight: 700;
}

dd {
  margin: 0 0 0.75em 1.25em;
  color: var(--ark-muted);
}

progress, meter {
  width: 100%;
  height: 0.6em;
  accent-color: var(--ark-accent);
}

output {
  font-weight: 600;
}

dialog {
  border: 1px solid var(--ark-border);
  border-radius: 12px;
  padding: 1.5rem 1.75rem;
  max-width: min(90vw, 32rem);
}

dialog::backdrop {
  background: rgba(26, 26, 46, 0.4);
}

kbd {
  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, "Liberation Mono", monospace;
  font-size: 0.85em;
  background: var(--ark-bg);
  border: 1px solid var(--ark-border);
  border-bottom-width: 2px;
  border-radius: 4px;
  padding: 0.1em 0.4em;
}

samp, var {
  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, "Liberation Mono", monospace;
  font-size: 0.9em;
}

dfn {
  font-style: italic;
}

address {
  font-style: normal;
  color: var(--ark-muted);
}

ruby {
  ruby-position: over;
}

rt {
  color: var(--ark-muted);
  font-size: 0.65em;
}

colgroup col.highlight {
  background: var(--ark-border);
}

iframe {
  max-width: 100%;
  border: 1px solid var(--ark-border);
  border-radius: 8px;
}

map, area {
  display: none; /* invisible hotspot layer over an <img>, nothing to lay out */
}

/* ------------------------------------------------------------------ */
/* v0.003 -- intrinsic responsive layout utilities.                    */
/*                                                                      */
/* ARKlight's `Page` never gets a `<head>` hook (see                   */
/* docs/DESIGN-NOTES.md), so there is no `@media`/`@container` query    */
/* available to any generated site -- responsiveness has to come from  */
/* the browser reflowing content from available width alone, not from  */
/* a rule keyed to a width threshold. These utility classes are the    */
/* standard, well-established answer to that constraint (the pattern   */
/* is sometimes called "intrinsic web design"): layouts that adapt      */
/* using only flexbox/grid sizing keywords (`minmax`, `auto-fit`,       */
/* `flex-wrap`, `clamp`), with no breakpoint ever written down. Opt in  */
/* with `class_name="stack"`, `class_name="cluster"`, etc. -- same       */
/* mechanism as `.nav`/`.card` above. */

/* Stack: consistent vertical rhythm between block children, no margin
   collapsing surprises. */
.stack > * + * {
  margin-top: var(--ark-stack-space, 1.25rem);
}

/* Cluster: a row of items that wraps as a group once it runs out of
   width -- nav bars, tag lists, button groups. */
.cluster {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: var(--ark-cluster-space, 0.75rem);
}

/* Sidebar: two panels that sit side-by-side once there's room for
   both, and stack vertically when there isn't -- no breakpoint, the
   flex-basis/grow math decides. */
.sidebar {
  display: flex;
  flex-wrap: wrap;
  gap: var(--ark-sidebar-space, 1.5rem);
}

.sidebar > :first-child {
  flex-basis: var(--ark-sidebar-width, 16rem);
  flex-grow: 1;
}

.sidebar > :last-child {
  flex-basis: 0;
  flex-grow: 999;
  min-width: 60%;
}

/* Switcher: children are stacked until the container is wide enough
   for all of them at a sensible minimum width, then they sit in a row
   -- a tab bar or a card row that becomes a stack on a narrow screen
   without ever checking the *screen's* width, only its own. */
.switcher {
  display: flex;
  flex-wrap: wrap;
  gap: var(--ark-switcher-space, 1rem);
}

.switcher > * {
  flex-grow: 1;
  flex-basis: calc((var(--ark-switcher-threshold, 30rem) - 100%) * 999);
}

/* Grid: an auto-filling card/tile grid with no explicit column count
   and no breakpoint -- the browser fits as many `minmax()`-wide
   columns as the available width allows. */
.grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(var(--ark-grid-min, 16rem), 1fr));
  gap: var(--ark-grid-space, 1.25rem);
}

/* Center: constrains and horizontally centers content, with optional
   inner gutters -- the "column" every `Page` already gets, available
   for use inside nested sections too. */
.center {
  max-width: var(--ark-center-width, 60ch);
  margin-left: auto;
  margin-right: auto;
  padding-left: var(--ark-center-gutter, 0);
  padding-right: var(--ark-center-gutter, 0);
}

/* Reel: a horizontally-scrolling row (image strips, card carousels)
   that never wraps or overflows the page -- an intrinsic alternative
   to a JS carousel. */
.reel {
  display: flex;
  gap: var(--ark-reel-space, 1rem);
  overflow-x: auto;
  scroll-snap-type: x proximity;
  padding-bottom: 0.5rem;
}

.reel > * {
  scroll-snap-align: start;
  flex: 0 0 auto;
}

/* Fluid heading: scales smoothly between a minimum and maximum size
   across the available width using `clamp()`, instead of jumping at a
   fixed breakpoint. */
.fluid-heading {
  font-size: clamp(1.75rem, 1.1rem + 2.5vw, 3rem);
  line-height: 1.15;
}

/* Pairs with the "dismiss" behavior (see arklight.backend.js): a
   banner/alert that a `Button` can permanently hide via
   `on_click="dismiss"`. */
.alert {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 1rem;
  border: 1px solid var(--ark-border);
  border-left: 4px solid var(--ark-accent);
  border-radius: 8px;
  padding: 0.9em 1.1em;
  margin: 1em 0;
  background: var(--ark-border);
}
"""


def _render_root_and_property_rules(overrides: dict[str, str]) -> str:
    """
    Generate the `:root { --ark-*: ...; }` block plus one `@property`
    block per variable, merging `overrides` (from `Site(max_width=...,
    bg=...)`, i.e. `ir.css_var_overrides`) over ROOT_VAR_DEFAULTS.

    `@property`'s `initial-value` is always the *default*, not whatever
    override is active -- per spec it's the fallback used before any
    value (including the `:root` declaration itself) is assigned, not a
    mirror of the current value, and it must be a value the declared
    `syntax` can parse on its own.
    """
    root_lines = [":root {"]
    for var_name, default in ROOT_VAR_DEFAULTS.items():
        value = overrides.get(var_name, default)
        root_lines.append(f"  {var_name}: {value};")
    root_lines.append("}")

    property_blocks = []
    for var_name, default in ROOT_VAR_DEFAULTS.items():
        syntax = ROOT_VAR_SYNTAX[var_name]
        property_blocks.append(
            f"@property {var_name} {{\n"
            f"  syntax: {syntax};\n"
            f"  inherits: true;\n"
            f"  initial-value: {default};\n"
            f"}}"
        )

    return "\n".join(root_lines) + "\n\n" + "\n\n".join(property_blocks)


def _render_custom_styles(custom_styles: dict[str, dict[str, str]]) -> str:
    """
    Turn `site.style(name, {prop: value})` registrations (v0.042) into
    real `.name { prop: value; ... }` CSS blocks, sorted by class name
    for deterministic output across runs. Empty input -> empty string
    (nothing appended to the stylesheet).
    """
    if not custom_styles:
        return ""

    blocks = [
        "\n/* Custom classes -- registered via `site.style(...)`. */",
    ]
    for class_name in sorted(custom_styles):
        rules = custom_styles[class_name]
        lines = [f".{class_name} {{"]
        for prop in sorted(rules):
            lines.append(f"  {prop}: {rules[prop]};")
        lines.append("}")
        blocks.append("\n".join(lines))
    return "\n\n".join(blocks) + "\n"


class CSSBackend(Backend):
    name = "css"

    def render(self, ir: WebsiteIR) -> dict[str, str]:
        # v0.002 ships a single, site-wide stylesheet; v0.042 appends
        # any custom classes a site registered via `site.style(...)`
        # (see `ir.custom_styles`, threaded from `Site.custom_styles`
        # through `build_website_ir`) after the fixed base stylesheet,
        # so custom classes can override base rules by cascade order.
        #
        # CSS backend refactor: `:root` (+ its `@property` typing) is no
        # longer part of the static BASE_CSS constant -- it's generated
        # here from ROOT_VAR_DEFAULTS merged with `ir.css_var_overrides`
        # (threaded from `Site(max_width=..., bg=...)`), so those two
        # variables are finally reachable from site code instead of
        # baked in. Everything else in BASE_CSS_BODY is unchanged.
        root_and_properties = _render_root_and_property_rules(ir.css_var_overrides)
        css = (
            BASE_CSS_HEADER
            + "\n"
            + root_and_properties
            + "\n\n"
            + BASE_CSS_BODY
            + _render_custom_styles(ir.custom_styles)
        )
        return {STYLESHEET_PATH: css}
