"""
CSS Backend.

v0.002 milestone. ARKlight ships one global stylesheet by default so a
freshly-generated site looks intentional out of the box, with zero CSS
written by the user -- matching "beginner friendly" and "Flask-like
simplicity". It targets the same tag mapping the HTML backend uses
(h1-h6, p, button, a, div, ul/li), plus a couple of small utility
classes (`.nav`, `.page`) that the built-in components can opt into via
the `class_name` prop.

Per-node customization doesn't require touching this file: any
component can carry a `style={...}` dict prop (rendered as an inline
`style` attribute by the HTML backend) or a `class_name="..."` prop
(rendered as `class`) to layer custom rules or override these defaults.

This is intentionally a static, constant stylesheet for v0.002 --
no per-node CSS generation yet. That's a natural place to extend later
(e.g. collecting `style=` props into real CSS rules instead of inline
styles) without changing the Backend interface.
"""

from __future__ import annotations

from arklight.backend.base import Backend
from arklight.ir.build import WebsiteIR

# Where the HTML backend expects to find the generated stylesheet,
# relative to the output directory root. Shared as a constant so both
# backends agree on the filename without importing each other's
# rendering internals.
STYLESHEET_PATH = "styles.css"

BASE_CSS = """\
/* Generated by ARKlight -- v0.002 default stylesheet.
   Override any of this with `style={...}` or `class_name="..."` props
   on your components. */

:root {
  --ark-bg: #ffffff;
  --ark-text: #1a1a2e;
  --ark-muted: #5b5b76;
  --ark-accent: #4f46e5;
  --ark-accent-hover: #4338ca;
  --ark-border: #e5e5f0;
  --ark-max-width: 720px;
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  padding: 2.5rem 1.5rem 4rem;
  background: var(--ark-bg);
  color: var(--ark-text);
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial,
    sans-serif;
  line-height: 1.6;
  max-width: var(--ark-max-width);
  margin-left: auto;
  margin-right: auto;
}

h1, h2, h3, h4, h5, h6 {
  line-height: 1.25;
  margin: 1.6em 0 0.5em;
  font-weight: 700;
  letter-spacing: -0.01em;
}

h1 { font-size: 2.25rem; margin-top: 0; }
h2 { font-size: 1.75rem; }
h3 { font-size: 1.4rem; }
h4 { font-size: 1.15rem; }
h5 { font-size: 1rem; }
h6 { font-size: 0.9rem; text-transform: uppercase; letter-spacing: 0.05em; color: var(--ark-muted); }

p {
  margin: 0 0 1em;
  color: var(--ark-text);
}

a {
  color: var(--ark-accent);
  text-decoration: none;
}

a:hover {
  color: var(--ark-accent-hover);
  text-decoration: underline;
}

button {
  font: inherit;
  background: var(--ark-accent);
  color: #ffffff;
  border: none;
  border-radius: 8px;
  padding: 0.65em 1.4em;
  cursor: pointer;
  transition: background 0.15s ease;
}

button:hover {
  background: var(--ark-accent-hover);
}

ul {
  padding-left: 1.25em;
  margin: 0 0 1em;
}

li {
  margin: 0.25em 0;
}

img {
  max-width: 100%;
  border-radius: 8px;
}

div {
  margin: 0;
}

/* Utility classes available to any component via class_name="..." */

.nav {
  display: flex;
  gap: 1.25rem;
  padding-bottom: 1.5rem;
  margin-bottom: 1.5rem;
  border-bottom: 1px solid var(--ark-border);
}

.nav a {
  color: var(--ark-text);
  font-weight: 600;
}

.nav a:hover {
  color: var(--ark-accent);
}

.nav a.is-active {
  color: var(--ark-accent);
}

.page {
  padding: 0;
}

/* Pairs with the "toggle" behavior (see arklight.backend.js): start an
   element hidden with class_name="hidden", then toggle_class="hidden"
   on the button that reveals it. */
.hidden {
  display: none;
}

.muted {
  color: var(--ark-muted);
}

.card {
  border: 1px solid var(--ark-border);
  border-radius: 12px;
  padding: 1.25rem 1.5rem;
  margin: 1em 0;
}
"""


class CSSBackend(Backend):
    name = "css"

    def render(self, ir: WebsiteIR) -> dict[str, str]:
        # v0.002 ships a single, site-wide stylesheet. `ir` isn't
        # consulted yet -- reserved for a future per-node style
        # collection pass -- but is accepted to satisfy the Backend
        # interface and keep this backend swappable with a smarter one.
        del ir
        return {STYLESHEET_PATH: BASE_CSS}
